export enum ServiceName {
  Shape = "shape",
  Location = "location",
  Hue = "hue",
  Saturation = "saturation",
  Lightness = "lightness",
  Alpha = "alpha",
  Size = "size",
  Draw = "draw",
  Bound = "bound",
  Window = "window",
  Rotation = "rotation",
  Jitter = "jitter",
  GlobalFireflyModifier = "global-firefly-modifier",
  Collision = "collision",
  Neighbourhood = "neighbourhood",
  Life = "life",
  /* === Speed === */
  SpeedX = "speedX",
  SpeedY = "speedY",
  PolarSpeedAngle = "polarSpeedAngle",
  PolarSpeedAmount = "polarSpeedAmount",
};