export enum ServiceName {
  Shape = "shape",
  Location = "location",
  Hue = "hue",
  Saturation = "saturation",
  Lightness = "lightness",
  Alpha = "alpha",
  Size = "size",
  Speed = "speed",
  Acceleration = "acceleration",
  Draw = "draw",
  Bound = "bound",
  Window = "window",
  Rotation = "rotation",
  Jitter = "jitter",
  GlobalFireflyModifier = "global-firefly-modifier",
  Collision = "collision",
  Neighbourhood = "neighbourhood",
  Life = "life"
};